### ISSUE TITLE
Widen constraint on cdoe_transformers

### ISSUE THREAD

**Issue by zoechi** [angular/di.dart#232]
The current constraint `<4.0` prevents me from publishing a version of https://pub.dartlang.org/packages/bwu_polymer_routing that is compatible with the latest Dart Polymer and reflectable package that fix some serious issues.
Current version of code_transformers is `0.4.1`

**Comment by zoechi** [comment]
I tried to change the dependency constraint

```
code_transformers: '>=0.3.1 <0.4.0'
```

Test utilities in the new `code_transformers` version were moved to the `transformer_test` package therefore I added `dev_dependency`

```
transformer_test: '^0.2.0'
```
and changed in `test/transforer_test.dart`

```
import 'package:code_transformers/tests.dart' as tests;
```
to
```
import 'package:transformer_test/utils.dart' as tests;
```

I run `./test_tf_gen.sh` and `./run-tests.sh`

runs 95 and 31 tests successfully but then fails with 

```
00:03 +31: All tests passed!
Building example...
No pubspec.lock file found, please run "pub get" first.
--------
PASS: Example transformer should not import dart:mirror
./run-tests.sh: Zeile 27: node: Kommando nicht gefunden.
./run-tests.sh: Zeile 28: [: ==: Einstelliger (unärer) Operator erwartet.
FAIL: Example transformer should inject dependencies
Tests failed. Build /example with `pub build example/ --mode debug` to debug.
```

Seems node is missing. I try to avoid to install it on my machine therefore I run the steps manually:
```
docker run -ti -v /home/zoechi/dart/dart-lang/di.dart/:/project node node /project/example/build/web/main.dart.js
```
output
> Success

```
cp test_assets/d8.js out/main.js
cat out/main.dart.js >> out/main.js
docker run -ti -v /home/zoechi/dart/dart-lang/di.dart/:/project node node /project/out/main.js
```
> 00:16 +92: All tests passed!

Temporarily change the 2nd-last line in `run-benchmarks.sh

```
 node out/$b.js
```
to
```
  docker run -ti -v /home/zoechi/dart/dart-lang/di.dart/:/project node bash -c "cd project && node out/$b.js"
```
but this fails

JS Benchmarks:
--------------
Running: module_benchmark.dart
/project/out/module_benchmark.dart.js:2
(function(){var supportsDirectProtoAccess=function(){var z=function(){}
^

> TypeError: this is not a function
    at Object.<anonymous> (/project/out/module_benchmark.dart.js:2:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

Giving up. I guess someone will run the tests and benchmarks again before merging.

**Comment by zoechi** [comment]
ping
